import {
  Globe,
  Crown,
  Flame,
  Cpu,
  Trophy,
  BookOpen,
  Zap,
  PieChart,
  ShieldAlert,
  Activity,
  BarChart3,
  TrendingUp,
  Radio,
  Sliders,
  Bell,
  RefreshCw,
} from "lucide-react";

export interface ModuleRegistryItem {
  id: string;
  label: string;
  icon: any;
  category: "Core" | "AI Intelligence" | "Signals" | "Market Data" | "Analytics" | "Tools" | "News" | "Admin";
  desc: string;
  emoji: string;
  tag: string;
  tagColor: string;
}

export const MODULE_REGISTRY: ModuleRegistryItem[] = [
  {
    id: "gmcgold",
    label: "👑 GMC GOLD Apex Bank-Zone Matrix (TOP #1)",
    icon: Crown,
    category: "Core",
    desc: "Top #1 Apex Bank-Zone liquidity matrix, Gold institutional order blocks & zone maps",
    emoji: "👑",
    tag: "TOP #1 APEX BANK-ZONE",
    tagColor: "bg-amber-400/30 text-amber-300 border-amber-400/80 shadow-[0_0_16px_rgba(234,179,8,0.6)] animate-pulse",
  },
  {
    id: "landing",
    label: "🌐 GMC TRADING AI™ Institutional Landing Portal",
    icon: Globe,
    category: "Core",
    desc: "Institutional public overview, features matrix & public AI architecture",
    emoji: "🌐",
    tag: "LANDING PORTAL",
    tagColor: "bg-blue-500/20 text-blue-300 border-blue-500/40",
  },
  {
    id: "d3heatmap",
    label: "🔥 GMC D3 Institutional Liquidity Heatmap",
    icon: Flame,
    category: "Core",
    desc: "Interactive D3 liquidity thermal map & real-time order book cluster radar",
    emoji: "🔥",
    tag: "D3 HEATMAP",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "gmccap",
    label: "⚡ GMC Alpha 1H Trend Command Engine",
    icon: Cpu,
    category: "Core",
    desc: "1-Hour H1 trend command engine with high precision institutional zones",
    emoji: "⚡",
    tag: "ALPHA H1 COMMAND",
    tagColor: "bg-amber-400/20 text-amber-300 border-amber-400/60 shadow-[0_0_12px_rgba(234,179,8,0.4)]",
  },
  {
    id: "harami",
    label: "⚔️ GMC Reversal Rejection Neural Radar",
    icon: Cpu,
    category: "Core",
    desc: "M15 order block reversal rejection neural radar with 99.1% Win Rate",
    emoji: "⚔️",
    tag: "REVERSAL RADAR",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "demoleaderboard",
    label: "🥇 GMC $5K Institutional Trader Hall",
    icon: Trophy,
    category: "Core",
    desc: "Live $5,000 demo account ranking & institutional trader performance matrix",
    emoji: "🥇",
    tag: "TRADER HALL",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "journal",
    label: "📓 GMC AI Precision Trade Logger & Analytics",
    icon: BookOpen,
    category: "AI Intelligence",
    desc: "AI trade logger, execution journal, risk metrics & performance analytics",
    emoji: "📓",
    tag: "PRECISION LOGGER",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "institutional",
    label: "🏛️ GMC Sovereign SMC Liquidity Desk",
    icon: Zap,
    category: "Core",
    desc: "Smart Money Concepts (SMC) order blocks & Fair Value Gap (FVG) scanner",
    emoji: "🏛️",
    tag: "SOVEREIGN SMC",
    tagColor: "bg-purple-500/20 text-purple-300 border-purple-500/40",
  },
  {
    id: "equitytracker",
    label: "📈 GMC Dynamic Portfolio Risk & Drawdown Monitor",
    icon: PieChart,
    category: "Analytics",
    desc: "Portfolio equity curve, dynamic drawdown monitor & risk metrics",
    emoji: "📈",
    tag: "EQUITY TRACKER",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "vault",
    label: "🏰 GMC Central Intelligence Vault & Archive",
    icon: Cpu,
    category: "Core",
    desc: "Central intelligence hub displaying all 38+ AI trading modules",
    emoji: "🏰",
    tag: "VAULT & ARCHIVE",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "masterbrain",
    label: "👑 GMC Sovereign AI Signal Fusion Core",
    icon: Cpu,
    category: "Core",
    desc: "Sovereign signal fusion core synthesizing multi-agent consensus",
    emoji: "👑",
    tag: "FUSION CORE",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "bond007",
    label: "🕵️‍♂️ GMC Secret Agent Order Block Sniper",
    icon: ShieldAlert,
    category: "Core",
    desc: "Secret agent order block sniper with London breaker reclaim timing",
    emoji: "🕵️‍♂️",
    tag: "SECRET AGENT",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "sentiment",
    label: "🎯 GMC Macro Sentiment & Order Flow Gauge",
    icon: Activity,
    category: "Core",
    desc: "Macro sentiment gauge & real-time order flow volume absorber",
    emoji: "🎯",
    tag: "ORDER FLOW GAUGE",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "heatmap",
    label: "🌋 GMC Deep Order Book Volatility Thermal",
    icon: Activity,
    category: "Core",
    desc: "Deep order book volatility thermal map & BSL/SSL pools radar",
    emoji: "🌋",
    tag: "VOLATILITY THERMAL",
    tagColor: "bg-blue-500/20 text-blue-400 border-blue-500/40",
  },
  {
    id: "comparative",
    label: "⚖️ GMC Cross-Asset Intermarket Scanner",
    icon: BarChart3,
    category: "Core",
    desc: "Cross-asset intermarket scanner (XAUUSD vs USD Index DXY correlation)",
    emoji: "⚖️",
    tag: "INTERMARKET SCAN",
    tagColor: "bg-purple-500/20 text-purple-300 border-purple-500/40",
  },
  {
    id: "blackshark",
    label: "🦈 GMC Apex Predator DOM & Depth Scanner",
    icon: Cpu,
    category: "Core",
    desc: "Apex predator depth of market (DOM) & order flow bid/ask wall scanner",
    emoji: "🦈",
    tag: "PREDATOR DOM",
    tagColor: "bg-blue-500/20 text-blue-400 border-blue-500/40",
  },
  {
    id: "aimaster",
    label: "🦁 GMC Vanguard 5-System Signal Matrix",
    icon: Zap,
    category: "Signals",
    desc: "Vanguard 5-system signal matrix ensemble (Command + AI + GMC + Meer + Snake)",
    emoji: "🦁",
    tag: "VANGUARD FUSION",
    tagColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  },
  {
    id: "breakout",
    label: "🚀 GMC Kinetic Momentum Breakout Radar",
    icon: TrendingUp,
    category: "Signals",
    desc: "Kinetic momentum breakout radar with advance zone retest signals",
    emoji: "🚀",
    tag: "MOMENTUM BREAKOUT",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "aibrain",
    label: "✨ GMC Quantum AI Trade Signal Director",
    icon: Cpu,
    category: "AI Intelligence",
    desc: "Quantum AI trade signal director with 69-voter consensus engine",
    emoji: "✨",
    tag: "QUANTUM DIRECTOR",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "chart",
    label: "📊 GMC Live Professional Charting Suite",
    icon: BarChart3,
    category: "Core",
    desc: "Live professional charting suite with multi-asset price action",
    emoji: "📊",
    tag: "CHARTING SUITE",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "tradelog",
    label: "📜 GMC Live Execution History & Ledger",
    icon: Cpu,
    category: "Analytics",
    desc: "Live execution history, order ledger & closed trade audit history",
    emoji: "📜",
    tag: "EXECUTION LEDGER",
    tagColor: "bg-slate-500/20 text-slate-300 border-slate-500/40",
  },
  {
    id: "metrics",
    label: "📉 GMC Quantitative Analytics & Win-Rate Lab",
    icon: PieChart,
    category: "Analytics",
    desc: "Quantitative win-rate lab & statistical edge analyzer",
    emoji: "📉",
    tag: "WIN-RATE LAB",
    tagColor: "bg-purple-500/20 text-purple-300 border-purple-500/40",
  },
  {
    id: "sniper",
    label: "🎯 GMC Micro Order Block Trigger Scanner",
    icon: Zap,
    category: "Signals",
    desc: "Micro order block trigger scanner for M1/M5 sniper entries",
    emoji: "🎯",
    tag: "ORDER BLOCK TRIGGER",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "nexus",
    label: "⚡ GMC Horizon Tactical Command Core",
    icon: Zap,
    category: "Signals",
    desc: "Horizon tactical command core with 10-agent council",
    emoji: "⚡",
    tag: "HORIZON COMMAND",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "mtfdoji",
    label: "🔮 GMC Multi-Layer Supply & Demand Grid",
    icon: Flame,
    category: "Signals",
    desc: "Multi-layer supply & demand grid with red doji testing alerts",
    emoji: "🔮",
    tag: "SUPPLY & DEMAND GRID",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "cipher",
    label: "🤖 GMC Cyber-Reactor ML Pattern Predictor",
    icon: Cpu,
    category: "Signals",
    desc: "Cyber-reactor ML pattern predictor for zone respect probabilities",
    emoji: "🤖",
    tag: "CYBER REACTOR ML",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "doji",
    label: "🐍 GMC Stealth Candle Reversal Trigger",
    icon: Flame,
    category: "Signals",
    desc: "Stealth candle reversal trigger with zone-lifecycle tracking",
    emoji: "🐍",
    tag: "STEALTH REVERSAL",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "smc",
    label: "🌊 GMC Structural Market Cycle Engine",
    icon: Zap,
    category: "Signals",
    desc: "Structural market cycle engine (BOS, CHoCH, Liquidity Sweeps)",
    emoji: "🌊",
    tag: "MARKET CYCLE",
    tagColor: "bg-blue-500/20 text-blue-400 border-blue-500/40",
  },
  {
    id: "falcon",
    label: "🦅 GMC Eagle-Eye Institutional Order Pilot",
    icon: Radio,
    category: "Signals",
    desc: "Eagle-eye institutional order pilot for high-altitude market scans",
    emoji: "🦅",
    tag: "EAGLE-EYE PILOT",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "brainspro",
    label: "🧠 GMC Multi-Agent AI Strategy Synthesizer",
    icon: Cpu,
    category: "AI Intelligence",
    desc: "Multi-agent AI strategy synthesizer & deep reasoning chains",
    emoji: "🧠",
    tag: "STRATEGY SYNTHESIZER",
    tagColor: "bg-purple-500/20 text-purple-300 border-purple-500/40",
  },
  {
    id: "satoshi",
    label: "🪙 GMC Digital Asset Crypto Macro Desk",
    icon: Radio,
    category: "Market Data",
    desc: "Digital asset crypto macro desk for Bitcoin & Ethereum",
    emoji: "🪙",
    tag: "CRYPTO MACRO",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "liquidity",
    label: "💧 GMC Market Liquidity & Depth Analyzer",
    icon: Activity,
    category: "Market Data",
    desc: "Market liquidity depth analyzer & stop pool clusters",
    emoji: "💧",
    tag: "DEPTH ANALYZER",
    tagColor: "bg-blue-500/20 text-blue-400 border-blue-500/40",
  },
  {
    id: "multitf",
    label: "📐 GMC Multi-Timeframe Trend Alignment Engine",
    icon: BarChart3,
    category: "Market Data",
    desc: "Multi-timeframe trend alignment engine (M5 to D1 trend sync)",
    emoji: "📐",
    tag: "TREND ALIGNMENT",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "whale",
    label: "🐳 GMC Whale Order Tracker & Big Money Radar",
    icon: Activity,
    category: "Market Data",
    desc: "Whale order tracker & big money institutional order radar",
    emoji: "🐳",
    tag: "WHALE RADAR",
    tagColor: "bg-blue-500/20 text-blue-400 border-blue-500/40",
  },
  {
    id: "news",
    label: "📅 GMC Global Macro Economic Desk",
    icon: Globe,
    category: "News",
    desc: "Global macro economic calendar & high impact news desk",
    emoji: "📅",
    tag: "MACRO NEWS",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "ainews",
    label: "📡 GMC AI Sentiment & Live Breaking Desk",
    icon: Globe,
    category: "News",
    desc: "AI sentiment & breaking economic news analyzer",
    emoji: "📡",
    tag: "AI NEWS DESK",
    tagColor: "bg-blue-500/20 text-blue-400 border-blue-500/40",
  },
  {
    id: "backtest",
    label: "🔬 GMC High-Frequency Quantitative Strategy Lab",
    icon: RefreshCw,
    category: "Tools",
    desc: "High-frequency quantitative strategy backtesting lab",
    emoji: "🔬",
    tag: "QUANT LAB",
    tagColor: "bg-purple-500/20 text-purple-300 border-purple-500/40",
  },
  {
    id: "risk",
    label: "🧮 GMC Capital Risk & Position Size Calculator",
    icon: Sliders,
    category: "Tools",
    desc: "Capital risk, position size & lot size calculator",
    emoji: "🧮",
    tag: "RISK CALCULATOR",
    tagColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
  },
  {
    id: "alerts",
    label: "🔔 GMC Intelligent Price Alert Dispatcher",
    icon: Bell,
    category: "Tools",
    desc: "Intelligent price alert dispatcher & threshold notifier",
    emoji: "🔔",
    tag: "ALERT DISPATCHER",
    tagColor: "bg-amber-500/20 text-amber-400 border-amber-500/40",
  },
  {
    id: "admin",
    label: "🛡️ GMC Enterprise Security & Admin Control Panel",
    icon: ShieldAlert,
    category: "Admin",
    desc: "Enterprise security, user sessions & Telegram Bot control panel",
    emoji: "🛡️",
    tag: "ADMIN PANEL",
    tagColor: "bg-red-500/20 text-red-300 border-red-500/40",
  },
];

export function getModuleTitle(tabId: string): string {
  const item = MODULE_REGISTRY.find((m) => m.id === tabId);
  return item ? item.label : tabId;
}

export function getModuleInfo(tabId: string): ModuleRegistryItem | undefined {
  return MODULE_REGISTRY.find((m) => m.id === tabId);
}
